// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int apiversion_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int apiversion = 5;
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int readme_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int readme = 9;
	/// <summary>PID: 20 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int systemname_20 = 20;
	/// <summary>PID: 20 | Type: read</summary>
	public const int systemname = 20;
	/// <summary>PID: 21 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int serialnumber_21 = 21;
	/// <summary>PID: 21 | Type: read</summary>
	public const int serialnumber = 21;
	/// <summary>PID: 30 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int temp1_30 = 30;
	/// <summary>PID: 30 | Type: read</summary>
	public const int temp1 = 30;
	/// <summary>PID: 31 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int temp2_31 = 31;
	/// <summary>PID: 31 | Type: read</summary>
	public const int temp2 = 31;
	/// <summary>PID: 61001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int processsysteminformation_61001 = 61001;
	/// <summary>PID: 61001 | Type: read</summary>
	public const int processsysteminformation = 61001;
	/// <summary>PID: 61002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int processtemperatureinformation_61002 = 61002;
	/// <summary>PID: 61002 | Type: read</summary>
	public const int processtemperatureinformation = 61002;
	public class Write
	{
		/// <summary>PID: 55 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int apiversion_55 = 55;
		/// <summary>PID: 55 | Type: write</summary>
		public const int apiversion = 55;
		/// <summary>PID: 997 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanager_contextmenu_997 = 997;
		/// <summary>PID: 997 | Type: write</summary>
		public const int pollingmanager_contextmenu = 997;
		/// <summary>PID: 1054 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanager_interval_1054 = 1054;
		/// <summary>PID: 1054 | Type: write</summary>
		public const int pollingmanager_interval = 1054;
		/// <summary>PID: 1056 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanager_adminstatus_1056 = 1056;
		/// <summary>PID: 1056 | Type: write</summary>
		public const int pollingmanager_adminstatus = 1056;
	}
	public class Cpus
	{
		/// <summary>PID: 100</summary>
		public const int tablePid = 100;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 101</summary>
		public const int indexColumnPid = 101;
		public class Pid
		{
			/// <summary>PID: 101 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpusinstance_101 = 101;
			/// <summary>PID: 101 | Type: read</summary>
			public const int cpusinstance = 101;
			/// <summary>PID: 102 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpusdescription_102 = 102;
			/// <summary>PID: 102 | Type: read</summary>
			public const int cpusdescription = 102;
			/// <summary>PID: 103 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpustotal_103 = 103;
			/// <summary>PID: 103 | Type: read</summary>
			public const int cpustotal = 103;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpusinstance_101 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int cpusinstance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpusdescription_102 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int cpusdescription = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int cpustotal_103 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int cpustotal = 2;
		}
	}
	public class Interfaces
	{
		/// <summary>PID: 200</summary>
		public const int tablePid = 200;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 201</summary>
		public const int indexColumnPid = 201;
		public class Pid
		{
			/// <summary>PID: 201 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesinstance_201 = 201;
			/// <summary>PID: 201 | Type: read</summary>
			public const int interfacesinstance = 201;
			/// <summary>PID: 202 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesdescription_202 = 202;
			/// <summary>PID: 202 | Type: read</summary>
			public const int interfacesdescription = 202;
			/// <summary>PID: 203 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesstatus_203 = 203;
			/// <summary>PID: 203 | Type: read</summary>
			public const int interfacesstatus = 203;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesinstance_201 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int interfacesinstance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesdescription_202 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int interfacesdescription = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int interfacesstatus_203 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int interfacesstatus = 2;
		}
	}
	public class Vlans
	{
		/// <summary>PID: 300</summary>
		public const int tablePid = 300;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 301</summary>
		public const int indexColumnPid = 301;
		public class Pid
		{
			/// <summary>PID: 301 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlansid_301 = 301;
			/// <summary>PID: 301 | Type: read</summary>
			public const int vlansid = 301;
			/// <summary>PID: 302 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlansname_302 = 302;
			/// <summary>PID: 302 | Type: read</summary>
			public const int vlansname = 302;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlansid_301 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int vlansid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlansname_302 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int vlansname = 1;
		}
	}
	public class Vlanpvst
	{
		/// <summary>PID: 400</summary>
		public const int tablePid = 400;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 401</summary>
		public const int indexColumnPid = 401;
		public class Pid
		{
			/// <summary>PID: 401 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlanpvstid_401 = 401;
			/// <summary>PID: 401 | Type: read</summary>
			public const int vlanpvstid = 401;
			/// <summary>PID: 402 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlanpvststatus_402 = 402;
			/// <summary>PID: 402 | Type: read</summary>
			public const int vlanpvststatus = 402;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlanpvstid_401 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int vlanpvstid = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int vlanpvststatus_402 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int vlanpvststatus = 1;
		}
	}
	public class Pollingmanager
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_name_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int pollingmanager_name = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_id_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int pollingmanager_id = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_description_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int pollingmanager_description = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_interval_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int pollingmanager_interval = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_suggestedinterval_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int pollingmanager_suggestedinterval = 1005;
			/// <summary>PID: 1006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_adminstatus_1006 = 1006;
			/// <summary>PID: 1006 | Type: read</summary>
			public const int pollingmanager_adminstatus = 1006;
			/// <summary>PID: 1008 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpolledtime_1008 = 1008;
			/// <summary>PID: 1008 | Type: read</summary>
			public const int pollingmanager_lastpolledtime = 1008;
			/// <summary>PID: 1009 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollstatus_1009 = 1009;
			/// <summary>PID: 1009 | Type: read</summary>
			public const int pollingmanager_lastpollstatus = 1009;
			/// <summary>PID: 1010 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollstatusinfo_1010 = 1010;
			/// <summary>PID: 1010 | Type: read</summary>
			public const int pollingmanager_lastpollstatusinfo = 1010;
			/// <summary>PID: 1011 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollexecutiontime_1011 = 1011;
			/// <summary>PID: 1011 | Type: read</summary>
			public const int pollingmanager_lastpollexecutiontime = 1011;
			public class Write
			{
				/// <summary>PID: 1057 | Type: write</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int pollingmanager_poll_1057 = 1057;
				/// <summary>PID: 1057 | Type: write</summary>
				public const int pollingmanager_poll = 1057;
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_name_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int pollingmanager_name = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_id_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int pollingmanager_id = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_description_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int pollingmanager_description = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_interval_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int pollingmanager_interval = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_suggestedinterval_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int pollingmanager_suggestedinterval = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_adminstatus_1006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int pollingmanager_adminstatus = 5;
			/// <summary>IDX: 7 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpolledtime_1008 = 7;
			/// <summary>IDX: 7 | Type: read</summary>
			public const int pollingmanager_lastpolledtime = 7;
			/// <summary>IDX: 8 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollstatus_1009 = 8;
			/// <summary>IDX: 8 | Type: read</summary>
			public const int pollingmanager_lastpollstatus = 8;
			/// <summary>IDX: 9 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollstatusinfo_1010 = 9;
			/// <summary>IDX: 9 | Type: read</summary>
			public const int pollingmanager_lastpollstatusinfo = 9;
			/// <summary>IDX: 10 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanager_lastpollexecutiontime_1011 = 10;
			/// <summary>IDX: 10 | Type: read</summary>
			public const int pollingmanager_lastpollexecutiontime = 10;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 55  | Type: write | DISCREETS: 1.0 = Version1, 2.0 = Version2</summary>
	public System.Object Apiversion {get { return Protocol.GetParameter(55); }set { Protocol.SetParameter(55, value); }}
	/// <summary>PID: 997  | Type: write | DISCREETS: Enable = 1, Enable (Forced) = 2, Disable = 3, Disable (Forced) = 4, Poll = 5, Separator 1 = -1, Enable All = 11, Disable All = 12, Poll All = 13, Separator 2 = -2, Reset to Default = 21</summary>
	public System.Object Pollingmanager_contextmenu {get { return Protocol.GetParameter(997); }set { Protocol.SetParameter(997, value); }}
	/// <summary>PID: 1054  | Type: write</summary>
	public System.Object Pollingmanager_interval {get { return Protocol.GetParameter(1054); }set { Protocol.SetParameter(1054, value); }}
	/// <summary>PID: 1056  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Pollingmanager_adminstatus {get { return Protocol.GetParameter(1056); }set { Protocol.SetParameter(1056, value); }}
	/// <summary>PID: 1057  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanager_poll {get { return Protocol.GetParameter(1057); }set { Protocol.SetParameter(1057, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 100</summary>
	CpusQActionTable cpus { get; set; }
	/// <summary>PID: 200</summary>
	InterfacesQActionTable interfaces { get; set; }
	/// <summary>PID: 300</summary>
	VlansQActionTable vlans { get; set; }
	/// <summary>PID: 400</summary>
	VlanpvstQActionTable vlanpvst { get; set; }
	/// <summary>PID: 1000</summary>
	PollingmanagerQActionTable pollingmanager { get; set; }
	object Afterstartup_dummy { get; set; }
	object Apiversion_5 { get; set; }
	object Apiversion { get; set; }
	object Readme_9 { get; set; }
	object Readme { get; set; }
	object Systemname_20 { get; set; }
	object Systemname { get; set; }
	object Serialnumber_21 { get; set; }
	object Serialnumber { get; set; }
	object Temp1_30 { get; set; }
	object Temp1 { get; set; }
	object Temp2_31 { get; set; }
	object Temp2 { get; set; }
	object Apiversion_55 { get; set; }
	object Cpusinstance_101 { get; set; }
	object Cpusinstance { get; set; }
	object Cpusdescription_102 { get; set; }
	object Cpusdescription { get; set; }
	object Cpustotal_103 { get; set; }
	object Cpustotal { get; set; }
	object Interfacesinstance_201 { get; set; }
	object Interfacesinstance { get; set; }
	object Interfacesdescription_202 { get; set; }
	object Interfacesdescription { get; set; }
	object Interfacesstatus_203 { get; set; }
	object Interfacesstatus { get; set; }
	object Vlansid_301 { get; set; }
	object Vlansid { get; set; }
	object Vlansname_302 { get; set; }
	object Vlansname { get; set; }
	object Vlanpvstid_401 { get; set; }
	object Vlanpvstid { get; set; }
	object Vlanpvststatus_402 { get; set; }
	object Vlanpvststatus { get; set; }
	object Pollingmanager_runqaction_dummy { get; set; }
	object Pollingmanager_contextmenu_997 { get; set; }
	object Pollingmanager_contextmenu { get; set; }
	object Pollingmanager_name_1001 { get; set; }
	object Pollingmanager_name { get; set; }
	object Pollingmanager_id_1002 { get; set; }
	object Pollingmanager_id { get; set; }
	object Pollingmanager_description_1003 { get; set; }
	object Pollingmanager_description { get; set; }
	object Pollingmanager_interval_1004 { get; set; }
	object Pollingmanager_interval { get; set; }
	object Pollingmanager_suggestedinterval_1005 { get; set; }
	object Pollingmanager_suggestedinterval { get; set; }
	object Pollingmanager_adminstatus_1006 { get; set; }
	object Pollingmanager_adminstatus { get; set; }
	object Pollingmanager_lastpolledtime_1008 { get; set; }
	object Pollingmanager_lastpolledtime { get; set; }
	object Pollingmanager_lastpollstatus_1009 { get; set; }
	object Pollingmanager_lastpollstatus { get; set; }
	object Pollingmanager_lastpollstatusinfo_1010 { get; set; }
	object Pollingmanager_lastpollstatusinfo { get; set; }
	object Pollingmanager_lastpollexecutiontime_1011 { get; set; }
	object Pollingmanager_lastpollexecutiontime { get; set; }
	object Pollingmanager_interval_1054 { get; set; }
	object Pollingmanager_adminstatus_1056 { get; set; }
	object Pollingmanager_poll_1057 { get; set; }
	object Pollingmanager_poll { get; set; }
	object Processsysteminformation_61001 { get; set; }
	object Processsysteminformation { get; set; }
	object Processtemperatureinformation_61002 { get; set; }
	object Processtemperatureinformation { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 100</summary>
	public CpusQActionTable cpus { get; set; }
	/// <summary>PID: 200</summary>
	public InterfacesQActionTable interfaces { get; set; }
	/// <summary>PID: 300</summary>
	public VlansQActionTable vlans { get; set; }
	/// <summary>PID: 400</summary>
	public VlanpvstQActionTable vlanpvst { get; set; }
	/// <summary>PID: 1000</summary>
	public PollingmanagerQActionTable pollingmanager { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: 1.0 = Version1, 2.0 = Version2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Apiversion_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: 1.0 = Version1, 2.0 = Version2</summary>
	public System.Object Apiversion {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Readme_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read</summary>
	public System.Object Readme {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 20  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Systemname_20 {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 20  | Type: read</summary>
	public System.Object Systemname {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 21  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Serialnumber_21 {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 21  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Serialnumber {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Temp1_30 {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	public System.Object Temp1 {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 31  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Temp2_31 {get { return GetParameter(31); }set { SetParameter(31, value); }}
	/// <summary>PID: 31  | Type: read</summary>
	public System.Object Temp2 {get { return GetParameter(31); }set { SetParameter(31, value); }}
	/// <summary>PID: 55  | Type: write | DISCREETS: 1.0 = Version1, 2.0 = Version2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Apiversion_55 {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 101  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpusinstance_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 101  | Type: read</summary>
	public System.Object Cpusinstance {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpusdescription_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: read</summary>
	public System.Object Cpusdescription {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 103  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpustotal_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 103  | Type: read</summary>
	public System.Object Cpustotal {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 201  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesinstance_201 {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 201  | Type: read</summary>
	public System.Object Interfacesinstance {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 202  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesdescription_202 {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 202  | Type: read</summary>
	public System.Object Interfacesdescription {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesstatus_203 {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Interfacesstatus {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlansid_301 {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 301  | Type: read</summary>
	public System.Object Vlansid {get { return GetParameter(301); }set { SetParameter(301, value); }}
	/// <summary>PID: 302  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlansname_302 {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 302  | Type: read</summary>
	public System.Object Vlansname {get { return GetParameter(302); }set { SetParameter(302, value); }}
	/// <summary>PID: 401  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlanpvstid_401 {get { return GetParameter(401); }set { SetParameter(401, value); }}
	/// <summary>PID: 401  | Type: read</summary>
	public System.Object Vlanpvstid {get { return GetParameter(401); }set { SetParameter(401, value); }}
	/// <summary>PID: 402  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlanpvststatus_402 {get { return GetParameter(402); }set { SetParameter(402, value); }}
	/// <summary>PID: 402  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Vlanpvststatus {get { return GetParameter(402); }set { SetParameter(402, value); }}
	/// <summary>PID: 990  | Type: dummy</summary>
	public System.Object Pollingmanager_runqaction_dummy {get { return GetParameter(990); }set { SetParameter(990, value); }}
	/// <summary>PID: 997  | Type: write | DISCREETS: Enable = 1, Enable (Forced) = 2, Disable = 3, Disable (Forced) = 4, Poll = 5, Separator 1 = -1, Enable All = 11, Disable All = 12, Poll All = 13, Separator 2 = -2, Reset to Default = 21</summary>
	public System.Object Pollingmanager_contextmenu_997 {get { return GetParameter(997); }set { SetParameter(997, value); }}
	/// <summary>PID: 997  | Type: write | DISCREETS: Enable = 1, Enable (Forced) = 2, Disable = 3, Disable (Forced) = 4, Poll = 5, Separator 1 = -1, Enable All = 11, Disable All = 12, Poll All = 13, Separator 2 = -2, Reset to Default = 21</summary>
	public System.Object Pollingmanager_contextmenu {get { return Write.Pollingmanager_contextmenu; }set { Write.Pollingmanager_contextmenu = value; }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_name_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Pollingmanager_name {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_id_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Pollingmanager_id {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_description_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Pollingmanager_description {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_interval_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read</summary>
	public System.Object Pollingmanager_interval {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_suggestedinterval_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	public System.Object Pollingmanager_suggestedinterval {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1006  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_adminstatus_1006 {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1006  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Pollingmanager_adminstatus {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1008  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpolledtime_1008 {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1008  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	public System.Object Pollingmanager_lastpolledtime {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1009  | Type: read | DISCREETS: Failed = 0, Succeeded = 1 | EXCEPTIONS: Disabled = -1, Not yet Polled = -2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollstatus_1009 {get { return GetParameter(1009); }set { SetParameter(1009, value); }}
	/// <summary>PID: 1009  | Type: read | DISCREETS: Failed = 0, Succeeded = 1 | EXCEPTIONS: Disabled = -1, Not yet Polled = -2</summary>
	public System.Object Pollingmanager_lastpollstatus {get { return GetParameter(1009); }set { SetParameter(1009, value); }}
	/// <summary>PID: 1010  | Type: read | EXCEPTIONS: N/A = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollstatusinfo_1010 {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1010  | Type: read | EXCEPTIONS: N/A = -1</summary>
	public System.Object Pollingmanager_lastpollstatusinfo {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1011  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollexecutiontime_1011 {get { return GetParameter(1011); }set { SetParameter(1011, value); }}
	/// <summary>PID: 1011  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	public System.Object Pollingmanager_lastpollexecutiontime {get { return GetParameter(1011); }set { SetParameter(1011, value); }}
	/// <summary>PID: 1054  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_interval_1054 {get { return GetParameter(1054); }set { SetParameter(1054, value); }}
	/// <summary>PID: 1056  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_adminstatus_1056 {get { return GetParameter(1056); }set { SetParameter(1056, value); }}
	/// <summary>PID: 1057  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanager_poll_1057 {get { return GetParameter(1057); }set { SetParameter(1057, value); }}
	/// <summary>PID: 1057  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanager_poll {get { return Write.Pollingmanager_poll; }set { Write.Pollingmanager_poll = value; }}
	/// <summary>PID: 61001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Processsysteminformation_61001 {get { return GetParameter(61001); }set { SetParameter(61001, value); }}
	/// <summary>PID: 61001  | Type: read</summary>
	public System.Object Processsysteminformation {get { return GetParameter(61001); }set { SetParameter(61001, value); }}
	/// <summary>PID: 61002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Processtemperatureinformation_61002 {get { return GetParameter(61002); }set { SetParameter(61002, value); }}
	/// <summary>PID: 61002  | Type: read</summary>
	public System.Object Processtemperatureinformation {get { return GetParameter(61002); }set { SetParameter(61002, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		cpus = new CpusQActionTable(this, 100, "cpus");
		interfaces = new InterfacesQActionTable(this, 200, "interfaces");
		vlans = new VlansQActionTable(this, 300, "vlans");
		vlanpvst = new VlanpvstQActionTable(this, 400, "vlanpvst");
		pollingmanager = new PollingmanagerQActionTable(this, 1000, "pollingmanager");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class CpusQActionTable : QActionTable, IEnumerable<CpusQActionRow>
{
	public CpusQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<CpusQActionRow> GetEnumerator() { return new QActionTableEnumerator<CpusQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class InterfacesQActionTable : QActionTable, IEnumerable<InterfacesQActionRow>
{
	public InterfacesQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<InterfacesQActionRow> GetEnumerator() { return new QActionTableEnumerator<InterfacesQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class VlansQActionTable : QActionTable, IEnumerable<VlansQActionRow>
{
	public VlansQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<VlansQActionRow> GetEnumerator() { return new QActionTableEnumerator<VlansQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class VlanpvstQActionTable : QActionTable, IEnumerable<VlanpvstQActionRow>
{
	public VlanpvstQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<VlanpvstQActionRow> GetEnumerator() { return new QActionTableEnumerator<VlanpvstQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class PollingmanagerQActionTable : QActionTable, IEnumerable<PollingmanagerQActionRow>
{
	public PollingmanagerQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<PollingmanagerQActionRow> GetEnumerator() { return new QActionTableEnumerator<PollingmanagerQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class CpusQActionRow : QActionTableRow
{
	/// <summary>PID: 101 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpusinstance_101 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 101 | Type: read</summary>
	public System.Object Cpusinstance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpusdescription_102 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 102 | Type: read</summary>
	public System.Object Cpusdescription { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Cpustotal_103 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 103 | Type: read</summary>
	public System.Object Cpustotal { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	public CpusQActionRow() : base(0, 3) { }
	public CpusQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
	public static implicit operator CpusQActionRow(System.Object[] source) { return new CpusQActionRow(source); }
	public static implicit operator System.Object[](CpusQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class InterfacesQActionRow : QActionTableRow
{
	/// <summary>PID: 201 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesinstance_201 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 201 | Type: read</summary>
	public System.Object Interfacesinstance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 202 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesdescription_202 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 202 | Type: read</summary>
	public System.Object Interfacesdescription { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 203 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Interfacesstatus_203 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 203 | Type: read</summary>
	public System.Object Interfacesstatus { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	public InterfacesQActionRow() : base(0, 3) { }
	public InterfacesQActionRow(System.Object[] oRow) : base(0, 3, oRow) { }
	public static implicit operator InterfacesQActionRow(System.Object[] source) { return new InterfacesQActionRow(source); }
	public static implicit operator System.Object[](InterfacesQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class VlansQActionRow : QActionTableRow
{
	/// <summary>PID: 301 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlansid_301 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 301 | Type: read</summary>
	public System.Object Vlansid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 302 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlansname_302 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 302 | Type: read</summary>
	public System.Object Vlansname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	public VlansQActionRow() : base(0, 2) { }
	public VlansQActionRow(System.Object[] oRow) : base(0, 2, oRow) { }
	public static implicit operator VlansQActionRow(System.Object[] source) { return new VlansQActionRow(source); }
	public static implicit operator System.Object[](VlansQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class VlanpvstQActionRow : QActionTableRow
{
	/// <summary>PID: 401 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlanpvstid_401 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 401 | Type: read</summary>
	public System.Object Vlanpvstid { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 402 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Vlanpvststatus_402 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 402 | Type: read</summary>
	public System.Object Vlanpvststatus { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	public VlanpvstQActionRow() : base(0, 2) { }
	public VlanpvstQActionRow(System.Object[] oRow) : base(0, 2, oRow) { }
	public static implicit operator VlanpvstQActionRow(System.Object[] source) { return new VlanpvstQActionRow(source); }
	public static implicit operator System.Object[](VlanpvstQActionRow source) { return source.ToObjectArray(); }
}
/// <summary>IDX: 0</summary>
public class PollingmanagerQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_name_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Pollingmanager_name { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_id_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Pollingmanager_id { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_description_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Pollingmanager_description { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_interval_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Pollingmanager_interval { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_suggestedinterval_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Pollingmanager_suggestedinterval { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_adminstatus_1006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	public System.Object Pollingmanager_adminstatus { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1057 | Type: write</summary>
	public System.Object Pollingmanager_poll_1057 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 1057 | Type: write</summary>
	public System.Object Pollingmanager_poll { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 1008 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpolledtime_1008 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 1008 | Type: read</summary>
	public System.Object Pollingmanager_lastpolledtime { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 1009 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollstatus_1009 { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 1009 | Type: read</summary>
	public System.Object Pollingmanager_lastpollstatus { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 1010 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollstatusinfo_1010 { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 1010 | Type: read</summary>
	public System.Object Pollingmanager_lastpollstatusinfo { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 1011 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanager_lastpollexecutiontime_1011 { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	/// <summary>PID: 1011 | Type: read</summary>
	public System.Object Pollingmanager_lastpollexecutiontime { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	public PollingmanagerQActionRow() : base(0, 11) { }
	public PollingmanagerQActionRow(System.Object[] oRow) : base(0, 11, oRow) { }
	public static implicit operator PollingmanagerQActionRow(System.Object[] source) { return new PollingmanagerQActionRow(source); }
	public static implicit operator System.Object[](PollingmanagerQActionRow source) { return source.ToObjectArray(); }
}
}
