<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
		<PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\QAction_1\QAction_1.csproj" />
	</ItemGroup>
</Project>
